require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe YoddlesController do

  # This should return the minimal set of attributes required to create a valid
  # Yoddle. As you add validations to Yoddle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # YoddlesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all yoddles as @yoddles" do
      yoddle = Yoddle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:yoddles).should eq([yoddle])
    end
  end

  describe "GET show" do
    it "assigns the requested yoddle as @yoddle" do
      yoddle = Yoddle.create! valid_attributes
      get :show, {:id => yoddle.to_param}, valid_session
      assigns(:yoddle).should eq(yoddle)
    end
  end

  describe "GET new" do
    it "assigns a new yoddle as @yoddle" do
      get :new, {}, valid_session
      assigns(:yoddle).should be_a_new(Yoddle)
    end
  end

  describe "GET edit" do
    it "assigns the requested yoddle as @yoddle" do
      yoddle = Yoddle.create! valid_attributes
      get :edit, {:id => yoddle.to_param}, valid_session
      assigns(:yoddle).should eq(yoddle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Yoddle" do
        expect {
          post :create, {:yoddle => valid_attributes}, valid_session
        }.to change(Yoddle, :count).by(1)
      end

      it "assigns a newly created yoddle as @yoddle" do
        post :create, {:yoddle => valid_attributes}, valid_session
        assigns(:yoddle).should be_a(Yoddle)
        assigns(:yoddle).should be_persisted
      end

      it "redirects to the created yoddle" do
        post :create, {:yoddle => valid_attributes}, valid_session
        response.should redirect_to(Yoddle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved yoddle as @yoddle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Yoddle.any_instance.stub(:save).and_return(false)
        post :create, {:yoddle => {}}, valid_session
        assigns(:yoddle).should be_a_new(Yoddle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Yoddle.any_instance.stub(:save).and_return(false)
        post :create, {:yoddle => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested yoddle" do
        yoddle = Yoddle.create! valid_attributes
        # Assuming there are no other yoddles in the database, this
        # specifies that the Yoddle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Yoddle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => yoddle.to_param, :yoddle => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested yoddle as @yoddle" do
        yoddle = Yoddle.create! valid_attributes
        put :update, {:id => yoddle.to_param, :yoddle => valid_attributes}, valid_session
        assigns(:yoddle).should eq(yoddle)
      end

      it "redirects to the yoddle" do
        yoddle = Yoddle.create! valid_attributes
        put :update, {:id => yoddle.to_param, :yoddle => valid_attributes}, valid_session
        response.should redirect_to(yoddle)
      end
    end

    describe "with invalid params" do
      it "assigns the yoddle as @yoddle" do
        yoddle = Yoddle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Yoddle.any_instance.stub(:save).and_return(false)
        put :update, {:id => yoddle.to_param, :yoddle => {}}, valid_session
        assigns(:yoddle).should eq(yoddle)
      end

      it "re-renders the 'edit' template" do
        yoddle = Yoddle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Yoddle.any_instance.stub(:save).and_return(false)
        put :update, {:id => yoddle.to_param, :yoddle => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested yoddle" do
      yoddle = Yoddle.create! valid_attributes
      expect {
        delete :destroy, {:id => yoddle.to_param}, valid_session
      }.to change(Yoddle, :count).by(-1)
    end

    it "redirects to the yoddles list" do
      yoddle = Yoddle.create! valid_attributes
      delete :destroy, {:id => yoddle.to_param}, valid_session
      response.should redirect_to(yoddles_url)
    end
  end

end
